name: workout
description: "workout planner app."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  collection: ^1.18.0
  cloud_firestore: ^5.5.1
  cloud_functions: ^5.2.0
  image_picker: ^1.1.2
  android_intent_plus: ^5.2.0
  built_value: ^8.9.2

  confetti: ^0.8.0
  connectivity_plus: ^6.1.0
  cupertino_icons: ^1.0.8
  math_expressions: ^2.6.0
  vector_math: ^2.1.4
  recase: ^4.1.0
  scroll_pos: ^0.5.0
  clock: ^1.1.1
  dio: ^5.7.0
  date_time_plus: ^7.2.0
  device_info_plus: ^11.1.1
  extension: ^0.6.0
  faker: ^2.2.0
  firebase_app_check: ^0.3.1+7
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.0
  firebase_database: ^11.2.0
  firebase_ui_database: ^1.5.0
  firebase_ui_firestore: ^1.7.0
  flutter_spinkit: ^5.2.1
  flutter_bloc: ^8.1.6
  flutter_confetti: ^0.3.4
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.3
  flutter_plugin_android_lifecycle: ^2.0.23
  font_awesome_flutter: ^10.8.0
  ansi_styles: ^0.3.2+1
  args: ^2.6.0
  ci: ^0.1.0
  cli_util: ^0.4.2
  deep_pick: ^1.1.0
  platform: ^3.1.6
  pubspec_parse: ^1.3.0
  yaml: ^3.1.2
  fl_chart: ^0.69.2
  get: ^4.6.6
  google_fonts: ^6.2.1
  googleapis: ^13.2.0
  keyboard_actions: ^4.2.0
  intl: ^0.19.0
  lints: ^5.0.0
  package_info_plus: ^8.1.1
  path: ^1.9.0
  path_provider: ^2.1.5
  percent_indicator: ^4.2.4
  permission_handler: ^11.3.1
  provider: ^6.1.2
  plugin_platform_interface: ^2.1.8
  rxdart: ^0.28.0
  shared_preferences: ^2.3.3
  sqflite: ^2.4.1
  sqlite3_flutter_libs: ^0.5.27
  sqlite3: ^2.5.0
  syncfusion_flutter_charts: ^27.2.5
  share_plus: ^10.1.2
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  web: ^1.1.0
  xml: ^6.5.0
  qr_flutter: ^4.1.0
  logging: ^1.3.0

  loading_animation_widget: ^1.3.0
  responsive_framework: ^1.5.1
  weather_icons: ^3.0.0
  flutter_lints: ^5.0.0

  equatable: ^2.0.7
  crypto: ^3.0.6
  mockito: ^5.4.4

  icon: ^2.2.1
  animated_text_kit: ^4.2.2






# Splash screen yapılandırması
flutter_native_splash:
  color: "#121212"
  image: assets/logo_rect.png
  android: true
  ios: true
  fullscreen: true
  android_gravity: center
  ios_content_mode: center
  web: false

  android_12:
    # Android 12+ için splash screen ayarları
    image: assets/logo_rect.png
    icon_background_color: "#121212"
    image_dark: assets/logo_rect.png
    icon_background_color_dark: "#121212"
    # Logo etrafındaki beyaz alanı kaldırmak için
    branding_mode: bottom


flutter_launcher_icons:
  android: true
  image_path: "assets/logo_rect.png"

dev_dependencies:




flutter:




  assets:
    - android/app/src/main/res/
    - android/app/src/main/res/values/
    - android/app/src/main/res/drawable/
    - android/app/src/main/res/values-v31/
    - android/app/src/main/res/drawable-v21/
    - android/app/src/main/res/values-night/
    - android/app/src/main/res/drawable-hdpi/
    - android/app/src/main/res/drawable-mdpi/
    - android/app/src/main/res/drawable-xhdpi/
    - android/app/src/main/res/drawable-xxhdpi/
    - android/app/src/main/res/drawable-xxxhdpi/
    - android/app/src/main/res/values-night-v31/
    - android/app/src/main/res/drawable-night-hdpi/
    - android/app/src/main/res/drawable-night-mdpi/
    - android/app/src/main/res/drawable-night-xhdpi/
    - android/app/src/main/res/drawable-night-xxhdpi/
    - android/app/src/main/res/drawable-night-xxxhdpi/
    - pubspec.yaml
    - lib/generated/assets.dart
    - assets/
    - database/




  fonts:
    - family: PetitFormalScript
      fonts:
        - asset: fonts/PetitFormalScript-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf
        - asset: fonts/Roboto-BlackItalic.ttf
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-BoldItalic.ttf
        - asset: fonts/Roboto-Italic.ttf
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-LightItalic.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-MediumItalic.ttf
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Thin.ttf
        - asset: fonts/Roboto-ThinItalic.ttf
    - family: Staatliches
      fonts:
        - asset: fonts/Staatliches-Regular.ttf



  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

