name: workout
description: "workout planner app."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


  image_picker: ^1.1.2
  android_intent_plus: ^5.2.0
  built_value: ^8.9.2
  cloud_firestore: ^5.4.4
  cloud_functions: ^5.1.3
  confetti: ^0.8.0
  connectivity_plus: ^6.1.0
  cupertino_icons: ^1.0.8
  math_expressions: ^2.6.0
  vector_math: ^2.1.4
  recase: ^4.1.0
  scroll_pos: ^0.5.0
  clock: ^1.1.1
  dio: ^5.7.0
  date_time_plus: ^7.2.0
  device_info_plus: ^11.1.0
  extension: ^0.6.0
  faker: ^2.2.0
  firebase_app_check: ^0.3.1+3
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  firebase_ui_database: ^1.5.0
  firebase_ui_firestore: ^1.7.0
  flutter_spinkit: ^5.2.1
  flutter_bloc: ^8.1.6
  flutter_confetti: ^0.3.4
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.2
  flutter_plugin_android_lifecycle: ^2.0.23
  font_awesome_flutter: ^10.7.0
  ansi_styles: ^0.3.2+1
  args: ^2.6.0
  ci: ^0.1.0
  cli_util: ^0.4.1
  deep_pick: ^1.1.0
  platform: ^3.1.6
  pubspec_parse: ^1.3.0
  yaml: ^3.1.2
  fl_chart: ^0.69.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  googleapis: ^13.2.0
  keyboard_actions: ^4.2.0
  intl: ^0.19.0
  lints: ^5.0.0
  package_info_plus: ^8.1.0
  path: ^1.9.0
  path_provider: ^2.1.4
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  plugin_platform_interface: ^2.1.8
  responsive_framework: ^1.5.1
  rxdart: ^0.28.0
  shared_preferences: ^2.3.2
  sqflite: ^2.4.0
  sqlite3_flutter_libs: ^0.5.25
  sqlite3: ^2.4.6
  syncfusion_flutter_charts: ^27.1.53
  share_plus: ^10.1.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  web: ^1.1.0
  xml: ^6.5.0
  qr_flutter: ^4.1.0
  logging: ^1.3.0








dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
 
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:





  assets:
    - database/esek.db
    - assets/abs-96.png
    - assets/app_icon.png
    - assets/back-96.png
    - assets/chest-24.png
    - assets/chest-48.png
    - assets/chest-96.png
    - assets/dumbbell-24.png
    - assets/dumbbell-48.png
    - assets/dumbbell-96.png
    - assets/dumbbells.png
    - assets/ic_launcher.png
    - assets/leg-96.png
    - assets/muscle-96.png
    - assets/stopwatch.png
    - assets/test.jpg



  fonts:
    - family: PetitFormalScript
      fonts:
        - asset: fonts/PetitFormalScript-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf
        - asset: fonts/Roboto-BlackItalic.ttf
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-BoldItalic.ttf
        - asset: fonts/Roboto-Italic.ttf
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-LightItalic.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-MediumItalic.ttf
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Thin.ttf
        - asset: fonts/Roboto-ThinItalic.ttf
    - family: Staatliches
      fonts:
        - asset: fonts/Staatliches-Regular.ttf



  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

