// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'strength_within';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String BODY_COMPOSITION_MODEL = 'assets/ai_models/body_composition_model.tflite';
  static const String EXERCISE_PLAN = 'assets/ai_models/exercise_plan.tflite';
  static const String EXERCISE_PLAN_MODEL = 'assets/ai_models/exercise_plan_model.tflite';
  static const String FITNESS_MODEL = 'assets/ai_models/fitness_model.tflite';
  static const String FITNESS_MODEL_V1_CALORIES_BURNED = 'assets/ai_models/fitness_model_v1_calories_burned.tflite';
  static const String FITNESS_MODEL_V1_EXERCISE_PLAN = 'assets/ai_models/fitness_model_v1_exercise_plan.tflite';
  static const String FITNESS_MODEL_V1_SESSION_DURATION = 'assets/ai_models/fitness_model_v1_session_duration.tflite';
  static const String FITNESS_MODEL_V1_WORKOUT_TYPE = 'assets/ai_models/fitness_model_v1_workout_type.tflite';
}
