// ignore: dangling_library_doc_comments
/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class DatabaseRes {
  DatabaseRes._();

  static const String PLUGIN_NAME = 'strength_within';
  static const String PLUGIN_VERSION = '1.0.0+1';
}
